### ISSUE TITLE
Windows EOL parse error

### ISSUE THREAD

**Issue by oicchris** [ToruNiina/Boost.toml#1]
The [same issue that affected toml11 (Issue #16)](https://github.com/ToruNiina/toml11/issues/16) is currently affecting Boost.toml.  \r\n causes a parse error in toml::parse().

Error:
`toml::detail::parse_ml_table: invalid line appeared -> toml::detail::parse_key_value_pair: toml::detail::parse_key: the next token is not a key ->`

P.S.  Thank you very much for your hard work!  Awesome!

**Comment by ToruNiina** [comment]
Thank you for telling me about the problem!
I've changed the code to open a file stream in binary mode. This will fix the problem.

**Comment by oicchris** [comment]
Thank you very much for the fix!  I've tested it on my sample and it succeeds.
